Repository athul-7735/green-global-initiative, pull requests merged in 2025-03, with the labels that each got.

#16 NGGI - 97 sonar cube sonar lint integration
  .github/workflows/SonarQube.yml
  sonar-project.properties
Labels: enhancement

#17 NGGI-80 : Create Patch API for Admin Page
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/GrantsApplicationController.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/ApplicationDetails.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/request/ApplicationUpdateRequest.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/ApplicationDetailsRepo.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsApplicationService.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsApplicationServiceImpl.java
  green-global-initiative-api/src/main/resources/application.properties
Labels: code

#19 NGGI-74: Develop and Integrate admin approval page
  green-global-initiative-ui/Dockerfile
  green-global-initiative-ui/nginx.conf
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.html
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.scss
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.spec.ts
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.ts
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.scss
  green-global-initiative-ui/src/app/grants/services/grants.service.ts
Labels: code

#20 NGGI-98: Unit test cases of angular application
  green-global-initiative-ui/src/app/about-us/about-us.component.spec.ts
  green-global-initiative-ui/src/app/about-us/about-us.component.ts
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.spec.ts
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.spec.ts
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.ts
  green-global-initiative-ui/src/app/app.component.spec.ts
  green-global-initiative-ui/src/app/app.routes.ts
  green-global-initiative-ui/src/app/authentication/login/login.component.spec.ts
  green-global-initiative-ui/src/app/authentication/login/login.component.ts
  green-global-initiative-ui/src/app/authentication/signup/signup.component.spec.ts
  green-global-initiative-ui/src/app/authentication/signup/signup.component.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
  green-global-initiative-ui/src/app/grants/grants-routing.module.ts
  green-global-initiative-ui/src/app/grants/services/grants.service.spec.ts
  green-global-initiative-ui/src/app/grants/services/grants.service.ts
  green-global-initiative-ui/src/app/shared/guards/auth.guard.spec.ts
  green-global-initiative-ui/src/app/shared/guards/auth.guard.ts
  green-global-initiative-ui/src/app/shared/guards/role.guard.spec.ts
  green-global-initiative-ui/src/app/shared/guards/role.guard.ts
  green-global-initiative-ui/src/app/shared/header/header.component.spec.ts
  green-global-initiative-ui/src/app/shared/services/jwt-interceptor.service.spec.ts
  green-global-initiative-ui/tsconfig.spec.json
Labels: code

#21 NGGI-104: Bug fix identified during the testing API
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/GrantsApplicationController.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/dto/ApplicationDetailsDto.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/ApplicationDetails.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/request/ApplicationUpdateRequest.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsApplicationServiceImpl.java
Labels: code

#22 Feat(API Docker): #NGGI-74 update docker file
  .gitignore
  green-global-initiative-api/Dockerfile
  green-global-initiative-api/src/main/resources/application.properties
Labels: enhancement

#23 NGGI-102: Create api for contact us page
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/QueryController.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/ContactUs.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/request/QueryCreateRequest.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/ContactUsRepo.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/QueryService.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/QueryServiceImpl.java
Labels: code

#24 Feat(Testing): #NGGI-98 Write unit test cases Admin Dashboard Page
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.spec.ts
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.html
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.spec.ts
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.ts
  green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
Labels: code

#26 Feat(Testing): #NGGI-103- Write unit test cases part-2
  green-global-initiative-ui/src/app/authentication/signup/signup.component.spec.ts
  green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
Labels: code

#28 Feat(Testing): #NGGI-98 Update unit test cases.
  green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
  green-global-initiative-ui/src/app/contact-us/contactus.component.ts
  green-global-initiative-ui/src/app/contact-us/services/contactus.service.spec.ts
Labels: code

#31 NGGI-105: Bug fixing and unit testing
  green-global-initiative-api/docker-compose.yml
  green-global-initiative-api/pom.xml
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/SecurityConfig.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/SwaggerConfig.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/UserController.java
  green-global-initiative-api/src/test/java/com/atu/green_global_initiative_api/controller/UserControllerTest.java
  green-global-initiative-ui/Dockerfile
  green-global-initiative-ui/angular.json
  green-global-initiative-ui/karma.conf.js
  green-global-initiative-ui/package.json
  green-global-initiative-ui/src/app/about-us/about-us.component.html
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.html
  green-global-initiative-ui/src/app/app.component.ts
  green-global-initiative-ui/src/app/authentication/login/login.component.html
  green-global-initiative-ui/src/app/authentication/services/api.service.ts
  green-global-initiative-ui/src/app/authentication/services/auth.service.ts
  green-global-initiative-ui/src/app/authentication/signup/signup.component.html
  green-global-initiative-ui/src/app/contact-us/contactus.component.html
  green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
  green-global-initiative-ui/src/app/contact-us/services/contactus.service.spec.ts
  green-global-initiative-ui/src/app/contact-us/services/contactus.service.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.ts
  green-global-initiative-ui/src/app/grants/grants-details/grants-details.component.html
  green-global-initiative-ui/src/app/grants/services/grants.service.ts
  green-global-initiative-ui/src/app/home/home.component.html
  green-global-initiative-ui/src/app/shared/footer/footer.component.html
  green-global-initiative-ui/src/app/shared/header/header.component.html
  green-global-initiative-ui/src/app/shared/header/header.component.ts
  green-global-initiative-ui/src/environments/environment.dev.ts
  green-global-initiative-ui/src/environments/environment.local.ts
  green-global-initiative-ui/src/environments/environment.prod.ts
  green-global-initiative-ui/src/environments/environment.ts
  green-global-initiative-ui/src/main.ts
Labels: enhancement

#33 Pull Request: NGGI-110Java doc integration in the Backend code
  green-global-initiative-api/pom.xml
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/NausicaaGreenInitiativeApplication.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/CorsConfig.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/DevCorsConfig.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/ProdCorsConfig.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/SecurityConfig.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/GlobalExceptionController.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/GrantsApplicationController.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/GrantsController.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/QueryController.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/UserController.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/dto/ApplicationDetailsDto.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/dto/GrantsDto.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/dto/UserDetailsDto.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/exception/ResourceNotFoundException.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/ApplicationDetails.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/ContactUs.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/Grants.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/UserDetails.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/request/ApplicationCreateRequest.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/request/ApplicationUpdateRequest.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/request/LoginRequest.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/request/QueryCreateRequest.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/ApplicationDetailsRepo.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/ContactUsRepo.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/GrantsRepo.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/UserDetailsRepo.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/security/JwtFilter.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/security/JwtUtil.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsApplicationService.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsApplicationServiceImpl.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsService.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsServiceImpl.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/QueryService.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/QueryServiceImpl.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/UserService.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/UserServiceImpl.java
Labels: documentation, enhancement, code

#34 Enhancement(UI): #NGGI-105 Update Config Files
  green-global-initiative-ui/angular.json
  green-global-initiative-ui/public/favicon.ico
  green-global-initiative-ui/src/app/app.config.ts
  green-global-initiative-ui/src/app/shared/services/jwt-interceptor.service.ts
  green-global-initiative-ui/src/environments/environment.dev.ts
  green-global-initiative-ui/src/environments/environment.prod.ts
  green-global-initiative-ui/src/index.html
Labels: enhancement

#35 NGGI-106: write unit test cases part 3
  README.md
  green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
  green-global-initiative-ui/src/app/contact-us/contactus.component.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
  green-global-initiative-ui/src/app/grants/grants-details/grants-details.component.spec.ts
  green-global-initiative-ui/src/app/grants/services/grants.service.spec.ts
  green-global-initiative-ui/src/app/shared/guards/auth.guard.spec.ts
  green-global-initiative-ui/src/app/shared/guards/role.guard.spec.ts
Labels: code

#37 Integrate Custom Domain & Configure Ingress Controller for Traffic Routing
  Kubernetes-Manifest-Files/Backend-ingress/backend-ingress.yaml
  Kubernetes-Manifest-Files/Backend/deployment.yaml
  Kubernetes-Manifest-Files/Backend/service.yaml
  Kubernetes-Manifest-Files/Database/configmap.yaml
  Kubernetes-Manifest-Files/Database/deployment.yaml
  Kubernetes-Manifest-Files/Database/dockersecret.yaml
  Kubernetes-Manifest-Files/Database/pv.yaml
  Kubernetes-Manifest-Files/Database/pvc.yaml
  Kubernetes-Manifest-Files/Database/secret.yaml
  Kubernetes-Manifest-Files/Database/service.yaml
  Kubernetes-Manifest-Files/Database/sql-configmap.yaml
  Kubernetes-Manifest-Files/Frontend-ingress/frontend-ingress.yaml
  Kubernetes-Manifest-Files/frontend/deployment.yaml
  Kubernetes-Manifest-Files/frontend/service.yaml
  eks-cluster/module/vpc.tf
  green-global-initiative-api/docker-compose.yml
  green-global-initiative-api/pom.xml
  green-global-initiative-api/src/main/resources/application-development.properties
  green-global-initiative-api/src/main/resources/application-production.properties
Labels: enhancement, code

#39 NGGI-111: Backend unit testing
  .github/workflows/sonar-qube.yml
  green-global-initiative-api/pom.xml
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/DevCorsConfig.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/ApplicationDetailsRepo.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/GrantsRepo.java
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/UserDetailsRepo.java
  green-global-initiative-api/src/test/java/com/atu/green_global_initiative_api/config/DevCorsConfigTest.java
Labels: enhancement, code

#40 NGGI-90 Integrate OWASP Dependency Check Bot
  .github/workflows/dependency-check.yml
  green-global-initiative-api/pom.xml
Labels: documentation, enhancement, code

#42 Nggi 114 write unit test cases part 4
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.spec.ts
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.ts
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.ts
  green-global-initiative-ui/src/app/app.component.spec.ts
  green-global-initiative-ui/src/app/app.component.ts
  green-global-initiative-ui/src/app/authentication/services/api.service.spec.ts
  green-global-initiative-ui/src/app/authentication/services/auth.service.spec.ts
  green-global-initiative-ui/src/app/authentication/signup/signup.component.spec.ts
  green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
  green-global-initiative-ui/src/app/home/home.component.spec.ts
  green-global-initiative-ui/src/app/shared/guards/auth.guard.spec.ts
  green-global-initiative-ui/src/app/shared/guards/role.guard.spec.ts
  green-global-initiative-ui/src/app/shared/header/header.component.spec.ts
Labels: code

#43 NGGI-112:CI yaml file integration with all the tools frontend UI
  .github/workflows/frondend-ci-cd.yml
  .gitignore
  green-global-initiative-ui/Dockerfile
  green-global-initiative-ui/karma.conf.js
  green-global-initiative-ui/package-lock.json
  green-global-initiative-ui/package.json
Labels: enhancement

#46 NGGI-122: kubernetes-cluster-setup-system-architecture-revision
  .github/workflows/Backend-CI-CD.yml
  eks-cluster/module/vpc.tf
Labels: enhancement

#49 NGGI-122: Update the CICD workflow
  .github/workflows/dependency-check.yml
Labels: enhancement

#51 NGGI-124:integration-of-js-doc-ui-V2
  .github/workflows/frondend-ci-cd.yml
  eks-cluster/eks/backend.tf
Labels: bug, enhancement

#52 NGGI-126: Implement special reward for grants
  green-global-initiative-api/init.sql
  green-global-initiative-api/pom.xml
Labels: code

#53 Release: Merge develop with main branch v2
  .github/workflows/frondend-ci-cd.yml
  eks-cluster/eks/backend.tf
  green-global-initiative-api/init.sql
  green-global-initiative-api/pom.xml
Labels: code

#55 Merge develop into main branch
  green-global-initiative-ui/README.md
Labels: enhancement

#58 NGGI-126: Implement special reward for grants
  Kubernetes-Manifest-Files/Backend/deployment.yaml
  Kubernetes-Manifest-Files/frontend/deployment.yaml
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/SwaggerConfig.java
  green-global-initiative-api/src/main/resources/application-development.properties
  green-global-initiative-api/src/main/resources/application-local.properties
  green-global-initiative-api/src/main/resources/application-production.properties
  green-global-initiative-api/src/main/resources/application.properties
  green-global-initiative-ui/src/app/contact-us/contactus.component.html
  green-global-initiative-ui/src/app/contact-us/contactus.component.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.html
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.scss
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.ts
  green-global-initiative-ui/src/app/shared/footer/footer.component.html
  green-global-initiative-ui/src/app/shared/footer/footer.component.ts
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.html
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.scss
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.spec.ts
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.ts
Labels: code

#59 Merge develop into main branch v4
  green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/SwaggerConfig.java
  green-global-initiative-api/src/main/resources/application-development.properties
  green-global-initiative-api/src/main/resources/application-local.properties
  green-global-initiative-api/src/main/resources/application-production.properties
  green-global-initiative-api/src/main/resources/application.properties
  green-global-initiative-ui/src/app/contact-us/contactus.component.html
  green-global-initiative-ui/src/app/contact-us/contactus.component.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.html
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.scss
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.ts
  green-global-initiative-ui/src/app/shared/footer/footer.component.html
  green-global-initiative-ui/src/app/shared/footer/footer.component.ts
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.html
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.scss
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.spec.ts
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.ts
Labels: code

#62 NGGI-125-implement-cd-pipeline-yaml-configurations-backend
  Kubernetes-Manifest-Files/Backend/deployment.yaml
  Kubernetes-Manifest-Files/frontend/deployment.yaml
  green-global-initiative-api/docker-compose.yml
Labels: enhancement

#63 Merge develop into main branch v5
  green-global-initiative-api/docker-compose.yml
Labels: enhancement

#64 NGGI-120:implement-cd-pipeline-yaml-configurations-front-end_V2
  green-global-initiative-api/docker-compose.yml
  green-global-initiative-ui/Dockerfile
Labels: enhancement

#69 NGGI-120:Updating dockerfile to carryout the testing
  Kubernetes-Manifest-Files/Backend/deployment.yaml
  Kubernetes-Manifest-Files/frontend/deployment.yaml
  green-global-initiative-api/Dockerfile
  green-global-initiative-ui/Dockerfile
Labels: enhancement, code

#70 NGGI-125:Updating backend dockerfile to carryout the testing
  green-global-initiative-api/Dockerfile
Labels: enhancement, code

#74 Nggi 125 implement cd pipeline yaml configurations backend
  Kubernetes-Manifest-Files/Backend/deployment.yaml
  Kubernetes-Manifest-Files/frontend/deployment.yaml
  eks-cluster/eks/dev.tfvars
Labels: code

#75 Merge develop into main branch v8
  eks-cluster/eks/dev.tfvars
Labels: code

#76 NGGI-120:implement-cd-pipeline-yaml-configurations-front-end
  .github/workflows/Backend-CI-CD.yml
  .github/workflows/frondend-ci-cd.yml
  green-global-initiative-api/Dockerfile
  green-global-initiative-ui/Dockerfile
Labels: enhancement

#78 NGGI-126: Implement special reward for grants
  Kubernetes-Manifest-Files/Backend/deployment.yaml
  Kubernetes-Manifest-Files/frontend/deployment.yaml
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.ts
Labels: enhancement

#79 Merge develop into main branch v10
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.ts
Labels: enhancement

#80 NGGI-126: Implement special reward for grants
  Kubernetes-Manifest-Files/Database/sql-configmap.yaml
  Kubernetes-Manifest-Files/frontend/deployment.yaml
  green-global-initiative-api/init.sql
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.html
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.scss
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.ts
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.html
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.scss
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.ts
  green-global-initiative-ui/src/app/grants/grants-details/grants-details.component.ts
Labels: enhancement

#81 Merge develop into main branch v11
  Kubernetes-Manifest-Files/Database/sql-configmap.yaml
  green-global-initiative-api/init.sql
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.html
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.scss
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.ts
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.html
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.scss
  green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.ts
  green-global-initiative-ui/src/app/grants/grants-details/grants-details.component.ts
Labels: enhancement

#82 NGGI-126: Implement UI test cases
  Kubernetes-Manifest-Files/Backend/deployment.yaml
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.spec.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.spec.ts
Labels: enhancement

#83 Merge develop into main branch v12
  green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.spec.ts
  green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
  green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.spec.ts
Labels: enhancement

#84 NGGI-126: Update Docker Files
  Kubernetes-Manifest-Files/frontend/deployment.yaml
  green-global-initiative-api/Dockerfile
  green-global-initiative-ui/Dockerfile
Labels: enhancement

#85 Merge develop into main branch v12
  green-global-initiative-api/Dockerfile
  green-global-initiative-ui/Dockerfile
Labels: enhancement

#91 NGGI-126: Update Docker Files
  Kubernetes-Manifest-Files/Backend/deployment.yaml
  Kubernetes-Manifest-Files/frontend/deployment.yaml
  green-global-initiative-api/Dockerfile
  green-global-initiative-ui/Dockerfile
Labels: enhancement

#92 Merge develop into main branch v13
  green-global-initiative-api/Dockerfile
  green-global-initiative-ui/Dockerfile
Labels: enhancement
